name: CI/CD Pipeline for My App

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Kubernetes CLI
      uses: azure/setup-kubectl@v3

    - name: Validate Kubernetes YAML
      run: kubectl apply --dry-run=client -f k8s-manifests/deployment.yaml

    - name: Lint Kubernetes Manifests
      run: kubeval k8s-manifests/deployment.yaml

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Deploy to Kubernetes
      env:
        KUBECONFIG: ${{ secrets.KUBECONFIG }}
      run: |
        kubectl apply -f k8s-manifests/deployment.yaml

